config/routes.rb
Rails.application.routes.draw do
  resources :seo_files

  resources :page_identifiers

  resources :seo_validations

  resources :action_logs
  
  resources :brands

  resources :brandurldata

  resources :browsertypes

  resources :error_messages

  resources :offer_data_details

  resources :workers

  resources :locators
  
  resources :error_codes

  resources :pixel_tests

  resources :sessions

  match "/signout" => "sessions#destroy", via: :all
  match "/adauth" => "sessions#create", via: :all

  
  post "/:type/:id/pause" => "testsuites#pause"
  post "/:type/:id/resume" => "testsuites#resume"

  
  post 'locators/previewimport' => 'locators#previewimport'
  post 'locators/import' => 'locators#import'

  
  post 'pixel_tests/:pixelsuite/duplicate' => 'pixel_tests#duplicate'
  post 'pixels/previewimport' => 'pixel_tests#previewimport'
  post 'pixel_tests/previewimport' => 'pixel_tests#previewimport'
  post 'pixels/import' => 'pixel_tests#import'

  
  get 'test_config/vanity' => 'pixel_tests#index', suitetype: 'Vanity'
  get 'test_config/uci' => 'pixel_tests#index', suitetype: 'UCI'
  get 'test_config/seo' => 'pixel_tests#index', suitetype: 'seo'

  
  get 'test_run/new' => 'test_run#new'
  get 'test_run/:id' => 'test_run#show'
  patch 'test_run/:id' => 'test_run#updatenotes'
  post 'test_run/create/pixel' => 'test_run#create_run'
  post 'test_run/create/vanity' => 'test_run#create_run', suitetype: 'Vanity'
  post 'test_run/create/uci' => 'test_run#create_run', suitetype: 'UCI'
  post 'test_run/create/seo' => 'test_run#create_run', suitetype: 'seo'

  
  get 'cartdetails' => 'cartdetails#index'
  post 'cartdetails/:offercode' => 'cartdetails#create'
  get 'cartdetails/new' => 'cartdetails#new'
  get 'cartdetails/edit' => 'cartdetails#edit'
  patch 'cartdetails/:offercode' => 'cartdetails#update'
  delete 'cartdetails/:offercode' => 'cartdetails#delete'

  
  get 'api/pixels/:suite/url' => 'pixel_tests#url'
  post 'api/pixels/:suite/url' => 'pixel_tests#addurl'
  get 'api/pixels/:suite/url/:urlid/pixels' => 'pixel_tests#pixeldata'
  post 'api/pixels/:suite/url/:urlid/pixels' => 'pixel_tests#addpixeldata'
  
  
  get 'api/testurls/suite/:id' => 'api_test_url#suite'
  get 'api/testurls' => 'api_test_url#index'
  post 'api/testurls' => 'api_test_url#create'
  delete 'api/testurls/:id' => 'api_test_url#delete'
  post 'api/testurls/:id' => 'api_test_url#update'

  
  get 'api/pixeldata' => 'pixel_data#index'
  get 'api/pixeldata/url/:urlid' => 'pixel_data#for_url'
  post 'api/pixeldata' => 'pixel_data#create'
  delete 'api/pixeldata/:id' => 'pixel_data#delete'
  delete 'api/pixeldata/url/:urlid/:pixelname' => 'pixel_data#delete_by_url'
  post 'api/pixeldata/:id' => 'pixel_data#update'

  get 'testruns/index' => 'testruns#index'
  get 'testruns/show/:id' => 'testruns#show'
  get 'testruns/new' => 'testruns#new'
  patch 'testruns/:id' => 'testruns#updatenotes'

  get 'testsuites/pixels' => 'testsuites#index', suitetype: 'pixels'
  get 'testsuites/vanity' => 'testsuites#index', suitetype: 'Vanity'
  get 'testsuites/uci' => 'testsuites#index', suitetype: 'UCI'
  get 'testsuites/seo' => 'testsuites#index', suitetype: 'seo'
  get 'testsuites/pixels/new' => 'testsuites#new_pixel', suitetype: 'pixels'
  post 'testsuites/pixels' => 'testsuites#create', suitetype: 'pixels'

  get 'pixels' => 'testsuites#index', suitetype: 'pixels'

  get 'pixels/new' => 'pixel_tests#new'
  get 'vanity/new' => 'pixel_tests#new', suitetype: 'Vanity'
  get 'seo/new' => 'pixel_tests#new', suitetype: 'seo'
  get 'uci/new' => 'pixel_tests#new', suitetype: 'UCI'
  get 'pixels/:suite' => 'pixel_tests#show'
  post 'pixels/' => 'pixel_tests#create'
  get 'pixels/:suite/edit' => 'pixel_tests#edit'
  

  get 'schedule/new' => 'schedule#new'
  patch 'schedule/:id' => 'schedule#update'
  get 'schedule/:id' => 'schedule#show'
  get 'schedule/edit/:id' => 'schedule#edit'
  delete 'schedule/:id' => 'schedule#delete'
  post 'schedule/disable/:id' => 'schedule#disable'
  post 'schedule/enable/:id' => 'schedule#enable'
  post 'schedule/run/:id' => 'schedule#run'
  get 'schedule/' => 'schedule#index'

  get 'buyflow' => 'testsuites#index', suitetype: 'Buyflow'
  get 'vanity' => 'testsuites#index', suitetype: 'Vanity'
  get 'uci' => 'testsuites#index', suitetype: 'UCI'
  get 'offercode' => 'testsuites#index', suitetype: 'Offercode'
  get 'seo' => 'testsuites#index', suitetype: 'seo'

  
  get 'campaigns/:id/duplicate' => 'campaigns#duplicate'
  get 'campaigns/bybrand/:brand/:environment(.:format)' => 'campaigns#environment'
  get 'campaigns/bybrand/:brand(.:format)' => 'campaigns#brand'

  get '/testsuites/new/offercode' => 'testruns#new', type: 'offercode'
  get '/testsuites/new/buyflow' => 'testruns#new', type: 'buyflow'
  post '/testsuites/offercode/create' => 'testsuites#offercode_create', type: 'offercode'
  post '/testsuites/buyflow/create' => 'testsuites#buyflow_create', type: 'buyflow'

  post '/offerdata/deactivate/:brand/:campaign/:env/:platform' => 'offerdata#deactivate'
  post '/offerdata/update/' => 'offerdata#update'
  post '/offerdata/previewimport/' => 'offerdata#preview'
  get '/offerdata/import/' => 'offerdata#import'

  get '/queue' => 'testruns#simple_queue', suitetype: 'Queue'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#new'

  delete '/buyflow/:id/delete' => 'testsuites#destroy', type: 'buyflow'
  delete '/offercode/:id/delete' => 'testsuites#destroy', type: 'offercode'
  delete '/pixels/:id/delete' => 'testsuites#destroy', type: 'pixels'
  delete '/vanity/:id/delete' => 'testsuites#destroy', type: 'vanity'
  delete '/uci/:id/delete' => 'testsuites#destroy', type: 'uci'
  delete '/seo/:id/delete' => 'testsuites#destroy', type: 'seo'

  get '/download/:id' => 'testsuites#download'

  get '/admin' => 'dashboard#admin_dash'
  post '/admin' => 'dashboard#admin_dash'

  get 'schedule' => 'schedule#index'

  resources :testruns, type: ''

  resources :testsuites
  
  resources :offerdata

  resources :campaigns
  root 'dashboard#index'

end

app/controllers/dashboard_controller.rb
require 'open-uri'
class DashboardController < ApplicationController

	# setup default action for path
	def index
	  	# set the header message
	  	@headertext = "Dashboard"

	  	# session[:current_user_id] = 123

	  	# get data for buyflow results component
	  	@buyflow 	= TestSuites.where('SuiteType' => 'Buyflow').limit(5).order("id desc")

		# get data for offercode results component
		@offercode 	= TestSuites.where('SuiteType' => 'Offercode').limit(5).order("id desc")

		# get data for Pixels results component
		@pixels 	= TestSuites.where('SuiteType' => 'pixels').limit(5).order("id desc")
		# get data for Vanity results component
		@vanity 	= TestSuites.where('SuiteType' => 'Vanity').limit(5).order("id desc")
		# get data for UCI results component
		@ucitests 	= TestSuites.where('SuiteType' => 'UCI').limit(5).order("id desc")
		# get data for SEO results component
		@seo 	= TestSuites.where('SuiteType' => 'seo').limit(5).order("id desc")
	end
	
	##
	# Dashboard action for admins panel
	def admin_dash
		# Any admin dashboard data should be collected here.
		admin_only do
			require_relative Rails.root.join("lib/grotto/browser/grid_utilities.rb")
			# collect all the worker tasks
			@worker_lanes = Delayed_Job.all().where(:failed_at => nil)
			@grid_hub = Grid_Processes.where(:role => 'hub').first
			@grid_nodes = Grid_Processes.where.not(:role => 'hub').where.not(:role => 'proxy')
			@hub_status = GridUtilities.is_hub_online?(host: @grid_hub.ip, port:@grid_hub.port)
			@grid_nodes_status = {}
			@grid_nodes.each do |node|
				begin
					@grid_nodes_status[node.id] = open("http://#{node.ip}:#{node.port}/wd/hub/status").status[0] == "200" ? true : false
				rescue
					@grid_nodes_status[node.id] = false
				end				
			end
		end
	end
end

app/views/dashboard/_alt_recent_tests.html.erb
<!-- START OF dashboard/_recent_tests.html.erb -->
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"><strong>Recent <%= type %> tests</strong></h3>
	</div>
	<div class="panel-body" style="min-height:400px; background-color:#E6E6E6; padding:0px;">
		<%

cols = ['DateTime',
'Status',
'Brand',
'Test Suite Name',
'Environment',
'Platform',
'Campaign',
'Realm',
'Progress',

'Suite']
def get_color(testrun)
	case testrun["result"]
	when "Pass"
		return "success"
	when "Fail"
		return "danger"
	else
		return ""
	end
end
%>
<div style="overflow:auto">
<table class="table table-hover body-shadow" style="background-color:#FFF">
	<tr style="text-align:center;">
		<% cols.each do |col| %>
			<th style="text-align:center;"><%= col %></th>
		<% end %>
	</tr>
	<% suites.each do |run| %>
	<%
	passed_amount 	= 0
	passed_amount 	= (run['Pass']*100 / run['TotalTests']*100)/100 if(run['TotalTests'] != 0)
	remaining_hold 	= 0
	remaining_hold 	= 100 - ((run['Pass']*100 + run['Fail']*100) / run['TotalTests']*100)/100 if(run['TotalTests'] != 0)
	
	remaining 		= remaining_hold 
	failed_amount 	= 100 - (passed_amount + remaining) 


	%>
	<tr style="text-align:center;">
		<td><%= run["DateTime"]%></td>
		<td><%= run["Status"]%></td>
		<td><%= run["Brand"]%></td>
		<td><%= run["Test Suite Name"]%></td>
		<td><%= run["Environment"]%></td>
		<td><%= run["Platform"]%></td>
		<td><%= run["Campaign"]%></td>
		<td><%= run["realm"]%></td>
		<td><div class="progress">
			<div class="progress-bar  progress-bar-success" role="progressbar" aria-valuenow="70"
				aria-valuemin="0" aria-valuemax="100" style="width:<%= passed_amount  %>%" disabled>
			</div>
			<div class="progress-bar  progress-bar-danger" role="progressbar" aria-valuenow="70"
				aria-valuemin="0" aria-valuemax="100" style="width:<%= failed_amount  %>%" disabled>
			</div>
			<div class="progress-bar  progress-bar-info" role="progressbar" aria-valuenow="70"
				aria-valuemin="0" aria-valuemax="100" style="width:<%= remaining %>%" disabled>
			</div>
		</div></td>
		<td>
			<a href="/testsuites/<%= run.id %>">
				<button type="button" class="btn btn-default">
					Details
				</button>
			</a>
		</td>
	</tr>
	<% end %>

</table>
</div>
<div class="table" style="text-align:center;">
	<tr><td><a href="/<%= type.strip.downcase %>"><div class="btn btn-primary btn-small">Go to <%= type %> Test Suite View</div></a></td></tr>
</div>
	</div>
</div>
<!-- END OF dashboard/_recent_tests.html.erb -->

app/views/dashboard/_recent_tests.html.erb
<!-- START OF dashboard/_recent_tests.html.erb -->
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"><strong>Recent <%= type %> tests</strong></h3>
	</div>
	<div class="panel-body" style="min-height:400px; background-color:#E6E6E6; padding:0px;">
		<%

cols = ['DateTime',
'Status',
'Brand',
'Environment',
'Platform',
'Campaign',
'Realm',
'Progress',

'Suite']
def get_color(testrun)
	case testrun["result"]
	when "Pass"
		return "success"
	when "Fail"
		return "danger"
	else
		return ""
	end
end
%>
<div style="overflow:auto">
<table class="table table-hover body-shadow" style="background-color:#FFF">
	<tr style="text-align:center;">
		<% cols.each do |col| %>
			<th style="text-align:center;"><%= col %></th>
		<% end %>
	</tr>
	<% suites.each do |run| %>
	<%
	passed_amount 	= 0
	passed_amount 	= (run['Pass']*100 / run['TotalTests']*100)/100 if(run['TotalTests'] != 0)
	remaining_hold 	= 0
	remaining_hold 	= 100 - ((run['Pass']*100 + run['Fail']*100) / run['TotalTests']*100)/100 if(run['TotalTests'] != 0)
	
	remaining 		= remaining_hold 
	failed_amount 	= 100 - (passed_amount + remaining) 


	%>
	<tr style="text-align:center;">
		<td><%= run["DateTime"]%></td>
		<td><%= run["Status"]%></td>
		<td><%= run["Brand"]%></td>
		<td><%= run["Environment"]%></td>
		<td><%= run["Platform"]%></td>
		<td><%= run["Campaign"]%></td>
		<td><%= run["realm"]%></td>
		<td><div class="progress">
			<div class="progress-bar  progress-bar-success" role="progressbar" aria-valuenow="70"
				aria-valuemin="0" aria-valuemax="100" style="width:<%= passed_amount  %>%" disabled>
			</div>
			<div class="progress-bar  progress-bar-danger" role="progressbar" aria-valuenow="70"
				aria-valuemin="0" aria-valuemax="100" style="width:<%= failed_amount  %>%" disabled>
			</div>
			<div class="progress-bar  progress-bar-info" role="progressbar" aria-valuenow="70"
				aria-valuemin="0" aria-valuemax="100" style="width:<%= remaining %>%" disabled>
			</div>
		</div></td>
		<td>
			<a href="/testsuites/<%= run.id %>">
				<button type="button" class="btn btn-default">
					Details
				</button>
			</a>
		</td>
	</tr>
	<% end %>

</table>
</div>
<div class="table" style="text-align:center;">
	<tr><td><a href="/<%= type.strip.downcase %>"><div class="btn btn-primary btn-small">Go to <%= type %> Test Suite View</div></a></td></tr>
</div>
	</div>
</div>
<!-- END OF dashboard/_recent_tests.html.erb -->

app/views/dashboard/_unimplemented_module.html.erb
<!-- START OF dashboard/_unimplemented_module.html.erb -->
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"><strong>Recent <%= modulename %></strong></h3>
	</div>
	<div class="panel-body Center-Container" style="min-height:400px; text-align:center; position: relative; background-color: #E6E6E6; color:#5C5C5C;">
			<div style="width: 50%; height: 50%; overflow: auto; margin: auto; position: absolute; top: 0; left: 0; bottom: 0; right: 0;">
				<h1 style="">Not Implemented</h1>
				<p><%= modulename %> are not yet implemented</p>
		</div>
	</div>
</div>
<!-- END OF dashboard/_unimplemented_module.html.erb -->

app/views/dashboard/admin_dash.html.erb
<!-- START OF dashboard/admin_dash.html.erb -->
<script type="text/javascript">
	$( document ).ready(function() {
	    bodyele = $('body');
	    bodyele.attr('style', 'background-color:#f5f5f5');
	});
</script>
<div class='panel panel-primary'>
	<div class='panel-heading'>
		<h2>
			Admin Console
		</h2>
		<small>
			Server Time is currently: <%= Time.now().getlocal %>
		</small>
	</div>
	<div class='panel-body'>
		<div class='row'>
			<div class='col-md-3'>
				<ul class="list-group">
					<a href="http://<%= @grid_hub.ip %>:<%= @grid_hub.port %>/grid/console" class="list-group-item">
						Selenium Grid Console
					</a>
					<a href='https://www.grautomation.guthy-renker.com:8808/' class="list-group-item">
						Code Documentation Server
					</a>
					<a href='https://confluence.guthy-renker.com/display/DIG/Digital+QA+-+Automation' class="list-group-item">
						Confluence Documentation
					</a>
					<a href='/error_messages' class="list-group-item">
						Errors Log
					</a>
					<a href='/error_codes' class="list-group-item">
						Custom Error Codes
					</a>
				</ul>
			</div>
		</div>
	</div>
	<div class='panel-heading'>
		<h2>
			Workers
		</h2>
	</div>
	<div class='panel-body'>
		<h3> Workers Running: </h3>
		<br>
		<% if @worker_lanes.empty? %>
			No Workers have checked in with database
		<% else %>
			<% @worker_lanes.each do |worker| %>
				<%= worker.queue %>
			<% end %>
		<% end %>

		<br><br>

		<%= link_to "Worker Priority", workers_path, :class => 'btn btn-default' %>
	</div>
	<div class='panel-heading'>
		<h2>
			Grid Hub and Nodes
		</h2>
	</div>
	<div class='panel-body'>
		<div class='row'>
			<div class='col-md-3'>
				ONLY USE RELOAD AS NEEDED - Slows down the server for a moment if there are nodes down. We don't have a general heart beat check for this at this time.<br><br>
				<%= form_tag("/admin", method: "post") do %>
				    <button id="reload" class="btn btn-danger" name="reload_status" value="true">Reload</button>
				<% end %>

				<br><br>
				<table class="table table-condensed">
					<tr>
						<td><h3>Hub</h3></td>
						<td><h3><%= @grid_hub.ip %>:<%= @grid_hub.port %></h3></td>
						<td><h3><span class="label label-<%= @hub_status ? 'success': 'danger'%>"><%= @hub_status ? 'Online': 'Offline'%></span></h3></td>
					</tr>
					<% @grid_nodes.each do |node| %>
						<tr>
							<td><h3><%= node.role.capitalize %></h3></td>
							<td><h3><%= node.ip + ":" + node.port %></h3></td>
							<td><h3><span class="label label-<%= @grid_nodes_status[node.id] ? 'success': 'danger'%>"><%= @grid_nodes_status[node.id] ? 'Online': 'Offline'%></span></td>
						</tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>
<!-- END OF dashboard/admin_dash.html.erb -->

app/views/dashboard/index.html.erb
<!-- START OF dashboard/index.html.erb -->
<style>
.row-eq-height {
	display: -webkit-box;
	display: -webkit-flex;
	display: -ms-flexbox;
	display:         flex;
}

</style>
<div class="row row-eq-height visible-lg">
	<div class="col-lg-6">
		<div>
			<%= render partial: "recent_tests", locals: {suites: @buyflow, type: "Buyflow"} %>
		</div>
	</div>
	<div class="col-lg-6">
		<div>
			<%= render partial:"recent_tests", locals: {suites: @vanity, type: "Vanity"} %>
		</div>
	</div>
</div>

<div class="row row-eq-height visible-lg">
	<div class="col-lg-6">
		<div>
			<%= render partial:"recent_tests", locals: {suites: @ucitests, type: "UCI"} %>
		</div>
	</div>
	<div class="col-lg-6">
		<div>
			<%= render partial: "recent_tests", locals: {suites: @offercode, type: "Offercode"} %>
		</div>
	</div>
</div>
<div class="row row-eq-height visible-lg">
	<div class="col-lg-6">
		<div>
			<%= render partial:"alt_recent_tests", locals: {suites: @pixels, type: "Pixels"} %>
		</div>
	</div>
	<div class="col-lg-6">
		<div>
			<%= render partial:"recent_tests", locals: {suites: @seo, type: "seo"} %>
		</div>
	</div>
</div>

<div class="row hidden-lg">
	<div class="col-md-12 col-lg-6">
		<div>
			<%= render partial: "recent_tests", locals: {suites: @buyflow, type: "Buyflow"} %>
		</div>
	</div>
	<div class="col-md-12 col-lg-6">
		<div>
			<%= render partial:"recent_tests", locals: {suites: @vanity, type: "Vanity"} %>
		</div>
	</div>
</div>

<div class="row hidden-lg">
	<div class="col-md-12 col-lg-6">
		<div>
			<%= render partial:"recent_tests", locals: {suites: @ucitests, type: "UCI"} %>
		</div>
	</div>
	<div class="col-md-12 col-lg-6">
		<div>
			<%= render partial: "recent_tests", locals: {suites: @offercode, type: "Offercode"} %>
		</div>
	</div>
</div>
<div class="row hidden-lg">
	<div class="col-md-12 col-lg-12">
		<div>
			<%= render partial:"recent_tests", locals: {suites: @pixels, type: "Pixels"} %>
		</div>
	</div>
</div>
<!-- END OF dashboard/index.html.erb -->