config/routes.rb
Rails.application.routes.draw do
  resources :seo_files

  resources :page_identifiers

  resources :seo_validations

  resources :action_logs
  
  resources :brands

  resources :brandurldata

  resources :browsertypes

  resources :error_messages

  resources :offer_data_details

  resources :workers

  resources :locators
  
  resources :error_codes

  resources :pixel_tests

  resources :sessions

  match "/signout" => "sessions#destroy", via: :all
  match "/adauth" => "sessions#create", via: :all

  
  post "/:type/:id/pause" => "testsuites#pause"
  post "/:type/:id/resume" => "testsuites#resume"

  
  post 'locators/previewimport' => 'locators#previewimport'
  post 'locators/import' => 'locators#import'

  
  post 'pixel_tests/:pixelsuite/duplicate' => 'pixel_tests#duplicate'
  post 'pixels/previewimport' => 'pixel_tests#previewimport'
  post 'pixel_tests/previewimport' => 'pixel_tests#previewimport'
  post 'pixels/import' => 'pixel_tests#import'

  
  get 'test_config/vanity' => 'pixel_tests#index', suitetype: 'Vanity'
  get 'test_config/uci' => 'pixel_tests#index', suitetype: 'UCI'
  get 'test_config/seo' => 'pixel_tests#index', suitetype: 'seo'

  
  get 'test_run/new' => 'test_run#new'
  get 'test_run/:id' => 'test_run#show'
  patch 'test_run/:id' => 'test_run#updatenotes'
  post 'test_run/create/pixel' => 'test_run#create_run'
  post 'test_run/create/vanity' => 'test_run#create_run', suitetype: 'Vanity'
  post 'test_run/create/uci' => 'test_run#create_run', suitetype: 'UCI'
  post 'test_run/create/seo' => 'test_run#create_run', suitetype: 'seo'

  
  get 'cartdetails' => 'cartdetails#index'
  post 'cartdetails/:offercode' => 'cartdetails#create'
  get 'cartdetails/new' => 'cartdetails#new'
  get 'cartdetails/edit' => 'cartdetails#edit'
  patch 'cartdetails/:offercode' => 'cartdetails#update'
  delete 'cartdetails/:offercode' => 'cartdetails#delete'

  
  get 'api/pixels/:suite/url' => 'pixel_tests#url'
  post 'api/pixels/:suite/url' => 'pixel_tests#addurl'
  get 'api/pixels/:suite/url/:urlid/pixels' => 'pixel_tests#pixeldata'
  post 'api/pixels/:suite/url/:urlid/pixels' => 'pixel_tests#addpixeldata'
  
  
  get 'api/testurls/suite/:id' => 'api_test_url#suite'
  get 'api/testurls' => 'api_test_url#index'
  post 'api/testurls' => 'api_test_url#create'
  delete 'api/testurls/:id' => 'api_test_url#delete'
  post 'api/testurls/:id' => 'api_test_url#update'

  
  get 'api/pixeldata' => 'pixel_data#index'
  get 'api/pixeldata/url/:urlid' => 'pixel_data#for_url'
  post 'api/pixeldata' => 'pixel_data#create'
  delete 'api/pixeldata/:id' => 'pixel_data#delete'
  delete 'api/pixeldata/url/:urlid/:pixelname' => 'pixel_data#delete_by_url'
  post 'api/pixeldata/:id' => 'pixel_data#update'

  get 'testruns/index' => 'testruns#index'
  get 'testruns/show/:id' => 'testruns#show'
  get 'testruns/new' => 'testruns#new'
  patch 'testruns/:id' => 'testruns#updatenotes'

  get 'testsuites/pixels' => 'testsuites#index', suitetype: 'pixels'
  get 'testsuites/vanity' => 'testsuites#index', suitetype: 'Vanity'
  get 'testsuites/uci' => 'testsuites#index', suitetype: 'UCI'
  get 'testsuites/seo' => 'testsuites#index', suitetype: 'seo'
  get 'testsuites/pixels/new' => 'testsuites#new_pixel', suitetype: 'pixels'
  post 'testsuites/pixels' => 'testsuites#create', suitetype: 'pixels'

  get 'pixels' => 'testsuites#index', suitetype: 'pixels'

  get 'pixels/new' => 'pixel_tests#new'
  get 'vanity/new' => 'pixel_tests#new', suitetype: 'Vanity'
  get 'seo/new' => 'pixel_tests#new', suitetype: 'seo'
  get 'uci/new' => 'pixel_tests#new', suitetype: 'UCI'
  get 'pixels/:suite' => 'pixel_tests#show'
  post 'pixels/' => 'pixel_tests#create'
  get 'pixels/:suite/edit' => 'pixel_tests#edit'
  

  get 'schedule/new' => 'schedule#new'
  patch 'schedule/:id' => 'schedule#update'
  get 'schedule/:id' => 'schedule#show'
  get 'schedule/edit/:id' => 'schedule#edit'
  delete 'schedule/:id' => 'schedule#delete'
  post 'schedule/disable/:id' => 'schedule#disable'
  post 'schedule/enable/:id' => 'schedule#enable'
  post 'schedule/run/:id' => 'schedule#run'
  get 'schedule/' => 'schedule#index'

  get 'buyflow' => 'testsuites#index', suitetype: 'Buyflow'
  get 'vanity' => 'testsuites#index', suitetype: 'Vanity'
  get 'uci' => 'testsuites#index', suitetype: 'UCI'
  get 'offercode' => 'testsuites#index', suitetype: 'Offercode'
  get 'seo' => 'testsuites#index', suitetype: 'seo'

  
  get 'campaigns/:id/duplicate' => 'campaigns#duplicate'
  get 'campaigns/bybrand/:brand/:environment(.:format)' => 'campaigns#environment'
  get 'campaigns/bybrand/:brand(.:format)' => 'campaigns#brand'

  get '/testsuites/new/offercode' => 'testruns#new', type: 'offercode'
  get '/testsuites/new/buyflow' => 'testruns#new', type: 'buyflow'
  post '/testsuites/offercode/create' => 'testsuites#offercode_create', type: 'offercode'
  post '/testsuites/buyflow/create' => 'testsuites#buyflow_create', type: 'buyflow'

  post '/offerdata/deactivate/:brand/:campaign/:env/:platform' => 'offerdata#deactivate'
  post '/offerdata/update/' => 'offerdata#update'
  post '/offerdata/previewimport/' => 'offerdata#preview'
  get '/offerdata/import/' => 'offerdata#import'

  get '/queue' => 'testruns#simple_queue', suitetype: 'Queue'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#new'

  delete '/buyflow/:id/delete' => 'testsuites#destroy', type: 'buyflow'
  delete '/offercode/:id/delete' => 'testsuites#destroy', type: 'offercode'
  delete '/pixels/:id/delete' => 'testsuites#destroy', type: 'pixels'
  delete '/vanity/:id/delete' => 'testsuites#destroy', type: 'vanity'
  delete '/uci/:id/delete' => 'testsuites#destroy', type: 'uci'
  delete '/seo/:id/delete' => 'testsuites#destroy', type: 'seo'

  get '/download/:id' => 'testsuites#download'

  get '/admin' => 'dashboard#admin_dash'
  post '/admin' => 'dashboard#admin_dash'

  get 'schedule' => 'schedule#index'

  resources :testruns, type: ''

  resources :testsuites
  
  resources :offerdata

  resources :campaigns
  root 'dashboard#index'

end

app/models/page_identifier.rb
class PageIdentifier < ActiveRecord::Base
end

app/controllers/page_identifiers_controller.rb
class PageIdentifiersController < ApplicationController
  before_action :set_page_identifier, only: [:show, :edit, :update, :destroy]

  # GET /page_identifiers
  # GET /page_identifiers.json
  def index
    @page_identifiers = PageIdentifier.all
  end

  # GET /page_identifiers/1
  # GET /page_identifiers/1.json
  def show
  end

  # GET /page_identifiers/new
  def new
    @page_identifier = PageIdentifier.new
  end

  # GET /page_identifiers/1/edit
  def edit
  end

  # POST /page_identifiers
  # POST /page_identifiers.json
  def create
    @page_identifier = PageIdentifier.new(page_identifier_params)

    respond_to do |format|
      if @page_identifier.save
        format.html { redirect_to @page_identifier, notice: 'Page identifier was successfully created.' }
        format.json { render :show, status: :created, location: @page_identifier }
      else
        format.html { render :new }
        format.json { render json: @page_identifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_identifiers/1
  # PATCH/PUT /page_identifiers/1.json
  def update
    respond_to do |format|
      if @page_identifier.update(page_identifier_params)
        format.html { redirect_to @page_identifier, notice: 'Page identifier was successfully updated.' }
        format.json { render :show, status: :ok, location: @page_identifier }
      else
        format.html { render :edit }
        format.json { render json: @page_identifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_identifiers/1
  # DELETE /page_identifiers/1.json
  def destroy
    @page_identifier.destroy
    respond_to do |format|
      format.html { redirect_to page_identifiers_url, notice: 'Page identifier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_identifier
      @page_identifier = PageIdentifier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_identifier_params
      params.require(:page_identifier).permit(:page, :value)
    end
end

app/helpers/page_identifiers_helper.rb
module PageIdentifiersHelper
end

app/views/page_identifiers/_form.html.erb
<%= form_for(@page_identifier) do |f| %>
  <% if @page_identifier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page_identifier.errors.count, "error") %> prohibited this page_identifier from being saved:</h2>

      <ul>
      <% @page_identifier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page %><br>
    <%= f.text_field :page, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value, :class => 'form-control' %>
  </div>
  <div class="actions"><br><br>
    <%= f.submit :class => 'btn btn-primary' %><br><br>
  </div>
<% end %>

app/views/page_identifiers/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Editing page_identifier</h1>
  </div>

  <div class="panel-body">

<%= render 'form' %>

<%= link_to 'Show', @page_identifier, :class => "btn btn-primary" %><br><br>
<%= link_to 'Back', page_identifiers_path, :class => "btn btn-primary" %>
</div>
</div>

app/views/page_identifiers/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Listing page_identifiers</h1>
  </div>

  <div class="panel-body">

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Page</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @page_identifiers.each do |page_identifier| %>
      <tr>
        <td><%= page_identifier.page %></td>
        <td><%= page_identifier.value %></td>
        <td><%= link_to 'Show', page_identifier, :class => "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_page_identifier_path(page_identifier), :class => "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', page_identifier, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page identifier', new_page_identifier_path, :class => "btn btn-primary" %>
</div>
</div>

app/views/page_identifiers/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>New page_identifier</h1>
  </div>

  <div class="panel-body">

<%= render 'form' %>

<%= link_to 'Back', page_identifiers_path, :class => "btn btn-primary" %>
</div>
</div>

app/views/page_identifiers/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Show page_identifier</h1>
  </div>

  <div class="panel-body">
  	<p id="notice"><%= notice %></p>

<p>
  <strong>Page:</strong>
  <%= @page_identifier.page %>
</p>

<p>
  <strong>Value:</strong>
  <%= @page_identifier.value %>
</p>

<%= link_to 'Edit', edit_page_identifier_path(@page_identifier), :class => "btn btn-primary" %> <br><br>
<%= link_to 'Back', page_identifiers_path, :class => "btn btn-primary" %>
</div>
</div>