config/routes.rb
Rails.application.routes.draw do
  resources :seo_files

  resources :page_identifiers

  resources :seo_validations

  resources :action_logs
  
  resources :brands

  resources :brandurldata

  resources :browsertypes

  resources :error_messages

  resources :offer_data_details

  resources :workers

  resources :locators
  
  resources :error_codes

  resources :pixel_tests

  resources :sessions

  match "/signout" => "sessions#destroy", via: :all
  match "/adauth" => "sessions#create", via: :all

  
  post "/:type/:id/pause" => "testsuites#pause"
  post "/:type/:id/resume" => "testsuites#resume"

  
  post 'locators/previewimport' => 'locators#previewimport'
  post 'locators/import' => 'locators#import'

  
  post 'pixel_tests/:pixelsuite/duplicate' => 'pixel_tests#duplicate'
  post 'pixels/previewimport' => 'pixel_tests#previewimport'
  post 'pixel_tests/previewimport' => 'pixel_tests#previewimport'
  post 'pixels/import' => 'pixel_tests#import'

  
  get 'test_config/vanity' => 'pixel_tests#index', suitetype: 'Vanity'
  get 'test_config/uci' => 'pixel_tests#index', suitetype: 'UCI'
  get 'test_config/seo' => 'pixel_tests#index', suitetype: 'seo'

  
  get 'test_run/new' => 'test_run#new'
  get 'test_run/:id' => 'test_run#show'
  patch 'test_run/:id' => 'test_run#updatenotes'
  post 'test_run/create/pixel' => 'test_run#create_run'
  post 'test_run/create/vanity' => 'test_run#create_run', suitetype: 'Vanity'
  post 'test_run/create/uci' => 'test_run#create_run', suitetype: 'UCI'
  post 'test_run/create/seo' => 'test_run#create_run', suitetype: 'seo'

  
  get 'cartdetails' => 'cartdetails#index'
  post 'cartdetails/:offercode' => 'cartdetails#create'
  get 'cartdetails/new' => 'cartdetails#new'
  get 'cartdetails/edit' => 'cartdetails#edit'
  patch 'cartdetails/:offercode' => 'cartdetails#update'
  delete 'cartdetails/:offercode' => 'cartdetails#delete'

  
  get 'api/pixels/:suite/url' => 'pixel_tests#url'
  post 'api/pixels/:suite/url' => 'pixel_tests#addurl'
  get 'api/pixels/:suite/url/:urlid/pixels' => 'pixel_tests#pixeldata'
  post 'api/pixels/:suite/url/:urlid/pixels' => 'pixel_tests#addpixeldata'
  
  
  get 'api/testurls/suite/:id' => 'api_test_url#suite'
  get 'api/testurls' => 'api_test_url#index'
  post 'api/testurls' => 'api_test_url#create'
  delete 'api/testurls/:id' => 'api_test_url#delete'
  post 'api/testurls/:id' => 'api_test_url#update'

  
  get 'api/pixeldata' => 'pixel_data#index'
  get 'api/pixeldata/url/:urlid' => 'pixel_data#for_url'
  post 'api/pixeldata' => 'pixel_data#create'
  delete 'api/pixeldata/:id' => 'pixel_data#delete'
  delete 'api/pixeldata/url/:urlid/:pixelname' => 'pixel_data#delete_by_url'
  post 'api/pixeldata/:id' => 'pixel_data#update'

  get 'testruns/index' => 'testruns#index'
  get 'testruns/show/:id' => 'testruns#show'
  get 'testruns/new' => 'testruns#new'
  patch 'testruns/:id' => 'testruns#updatenotes'

  get 'testsuites/pixels' => 'testsuites#index', suitetype: 'pixels'
  get 'testsuites/vanity' => 'testsuites#index', suitetype: 'Vanity'
  get 'testsuites/uci' => 'testsuites#index', suitetype: 'UCI'
  get 'testsuites/seo' => 'testsuites#index', suitetype: 'seo'
  get 'testsuites/pixels/new' => 'testsuites#new_pixel', suitetype: 'pixels'
  post 'testsuites/pixels' => 'testsuites#create', suitetype: 'pixels'

  get 'pixels' => 'testsuites#index', suitetype: 'pixels'

  get 'pixels/new' => 'pixel_tests#new'
  get 'vanity/new' => 'pixel_tests#new', suitetype: 'Vanity'
  get 'seo/new' => 'pixel_tests#new', suitetype: 'seo'
  get 'uci/new' => 'pixel_tests#new', suitetype: 'UCI'
  get 'pixels/:suite' => 'pixel_tests#show'
  post 'pixels/' => 'pixel_tests#create'
  get 'pixels/:suite/edit' => 'pixel_tests#edit'
  

  get 'schedule/new' => 'schedule#new'
  patch 'schedule/:id' => 'schedule#update'
  get 'schedule/:id' => 'schedule#show'
  get 'schedule/edit/:id' => 'schedule#edit'
  delete 'schedule/:id' => 'schedule#delete'
  post 'schedule/disable/:id' => 'schedule#disable'
  post 'schedule/enable/:id' => 'schedule#enable'
  post 'schedule/run/:id' => 'schedule#run'
  get 'schedule/' => 'schedule#index'

  get 'buyflow' => 'testsuites#index', suitetype: 'Buyflow'
  get 'vanity' => 'testsuites#index', suitetype: 'Vanity'
  get 'uci' => 'testsuites#index', suitetype: 'UCI'
  get 'offercode' => 'testsuites#index', suitetype: 'Offercode'
  get 'seo' => 'testsuites#index', suitetype: 'seo'

  
  get 'campaigns/:id/duplicate' => 'campaigns#duplicate'
  get 'campaigns/bybrand/:brand/:environment(.:format)' => 'campaigns#environment'
  get 'campaigns/bybrand/:brand(.:format)' => 'campaigns#brand'

  get '/testsuites/new/offercode' => 'testruns#new', type: 'offercode'
  get '/testsuites/new/buyflow' => 'testruns#new', type: 'buyflow'
  post '/testsuites/offercode/create' => 'testsuites#offercode_create', type: 'offercode'
  post '/testsuites/buyflow/create' => 'testsuites#buyflow_create', type: 'buyflow'

  post '/offerdata/deactivate/:brand/:campaign/:env/:platform' => 'offerdata#deactivate'
  post '/offerdata/update/' => 'offerdata#update'
  post '/offerdata/previewimport/' => 'offerdata#preview'
  get '/offerdata/import/' => 'offerdata#import'

  get '/queue' => 'testruns#simple_queue', suitetype: 'Queue'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#new'

  delete '/buyflow/:id/delete' => 'testsuites#destroy', type: 'buyflow'
  delete '/offercode/:id/delete' => 'testsuites#destroy', type: 'offercode'
  delete '/pixels/:id/delete' => 'testsuites#destroy', type: 'pixels'
  delete '/vanity/:id/delete' => 'testsuites#destroy', type: 'vanity'
  delete '/uci/:id/delete' => 'testsuites#destroy', type: 'uci'
  delete '/seo/:id/delete' => 'testsuites#destroy', type: 'seo'

  get '/download/:id' => 'testsuites#download'

  get '/admin' => 'dashboard#admin_dash'
  post '/admin' => 'dashboard#admin_dash'

  get 'schedule' => 'schedule#index'

  resources :testruns, type: ''

  resources :testsuites
  
  resources :offerdata

  resources :campaigns
  root 'dashboard#index'

end

app/models/action_log.rb
class ActionLog < ActiveRecord::Base
end

app/controllers/action_logs_controller.rb
class ActionLogsController < ApplicationController
  before_action :set_action_log, only: [:show, :edit, :update, :destroy]

  # GET /action_logs
  # GET /action_logs.json
  def index
    @action_logs = ActionLog.all
  end

  # GET /action_logs/1
  # GET /action_logs/1.json
  def show
  end

  # GET /action_logs/new
  def new
    @action_log = ActionLog.new
  end

  # GET /action_logs/1/edit
  def edit
  end

  # POST /action_logs
  # POST /action_logs.json
  def create
    @action_log = ActionLog.new(action_log_params)

    respond_to do |format|
      if @action_log.save
        format.html { redirect_to @action_log, notice: 'Action log was successfully created.' }
        format.json { render :show, status: :created, location: @action_log }
      else
        format.html { render :new }
        format.json { render json: @action_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /action_logs/1
  # PATCH/PUT /action_logs/1.json
  def update
    respond_to do |format|
      if @action_log.update(action_log_params)
        format.html { redirect_to @action_log, notice: 'Action log was successfully updated.' }
        format.json { render :show, status: :ok, location: @action_log }
      else
        format.html { render :edit }
        format.json { render json: @action_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_logs/1
  # DELETE /action_logs/1.json
  def destroy
    @action_log.destroy
    respond_to do |format|
      format.html { redirect_to action_logs_url, notice: 'Action log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_action_log
      @action_log = ActionLog.find(params[:id])
    end

    # Never trust parameters from the internet, only allow the white list through.
    def action_log_params
      params.require(:action_log).permit(:user, :action, :target, :time_of_action)
    end
end

app/helpers/action_logs_helper.rb
module ActionLogsHelper
end

app/views/action_logs/_form.html.erb
<%= form_for(@action_log) do |f| %>
  <% if @action_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_log.errors.count, "error") %> prohibited this action_log from being saved:</h2>

      <ul>
      <% @action_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :target %><br>
    <%= f.text_field :target %>
  </div>
  <div class="field">
    <%= f.label :time_of_action %><br>
    <%= f.datetime_select :time_of_action %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/action_logs/edit.html.erb
<h1>Editing action_log</h1>

<%= render 'form' %>

<%= link_to 'Show', @action_log %> |
<%= link_to 'Back', action_logs_path %>

app/views/action_logs/index.html.erb
<h1>Listing action_logs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Action</th>
      <th>Target</th>
      <th>Time of action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @action_logs.each do |action_log| %>
      <tr>
        <td><%= action_log.user %></td>
        <td><%= action_log.action %></td>
        <td><%= action_log.target %></td>
        <td><%= action_log.time_of_action %></td>
        <td><%= link_to 'Show', action_log %></td>
        <td><%= link_to 'Edit', edit_action_log_path(action_log) %></td>
        <td><%= link_to 'Destroy', action_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Action log', new_action_log_path %>

app/views/action_logs/new.html.erb
<h1>New action_log</h1>

<%= render 'form' %>

<%= link_to 'Back', action_logs_path %>

app/views/action_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @action_log.user %>
</p>

<p>
  <strong>Action:</strong>
  <%= @action_log.action %>
</p>

<p>
  <strong>Target:</strong>
  <%= @action_log.target %>
</p>

<p>
  <strong>Time of action:</strong>
  <%= @action_log.time_of_action %>
</p>

<%= link_to 'Edit', edit_action_log_path(@action_log) %> |
<%= link_to 'Back', action_logs_path %>