config/routes.rb
Rails.application.routes.draw do
  resources :seo_files

  resources :page_identifiers

  resources :seo_validations

  resources :action_logs
  
  resources :brands

  resources :brandurldata

  resources :browsertypes

  resources :error_messages

  resources :offer_data_details

  resources :workers

  resources :locators
  
  resources :error_codes

  resources :pixel_tests

  resources :sessions

  match "/signout" => "sessions#destroy", via: :all
  match "/adauth" => "sessions#create", via: :all

  
  post "/:type/:id/pause" => "testsuites#pause"
  post "/:type/:id/resume" => "testsuites#resume"

  
  post 'locators/previewimport' => 'locators#previewimport'
  post 'locators/import' => 'locators#import'

  
  post 'pixel_tests/:pixelsuite/duplicate' => 'pixel_tests#duplicate'
  post 'pixels/previewimport' => 'pixel_tests#previewimport'
  post 'pixel_tests/previewimport' => 'pixel_tests#previewimport'
  post 'pixels/import' => 'pixel_tests#import'

  
  get 'test_config/vanity' => 'pixel_tests#index', suitetype: 'Vanity'
  get 'test_config/uci' => 'pixel_tests#index', suitetype: 'UCI'
  get 'test_config/seo' => 'pixel_tests#index', suitetype: 'seo'

  
  get 'test_run/new' => 'test_run#new'
  get 'test_run/:id' => 'test_run#show'
  patch 'test_run/:id' => 'test_run#updatenotes'
  post 'test_run/create/pixel' => 'test_run#create_run'
  post 'test_run/create/vanity' => 'test_run#create_run', suitetype: 'Vanity'
  post 'test_run/create/uci' => 'test_run#create_run', suitetype: 'UCI'
  post 'test_run/create/seo' => 'test_run#create_run', suitetype: 'seo'

  
  get 'cartdetails' => 'cartdetails#index'
  post 'cartdetails/:offercode' => 'cartdetails#create'
  get 'cartdetails/new' => 'cartdetails#new'
  get 'cartdetails/edit' => 'cartdetails#edit'
  patch 'cartdetails/:offercode' => 'cartdetails#update'
  delete 'cartdetails/:offercode' => 'cartdetails#delete'

  
  get 'api/pixels/:suite/url' => 'pixel_tests#url'
  post 'api/pixels/:suite/url' => 'pixel_tests#addurl'
  get 'api/pixels/:suite/url/:urlid/pixels' => 'pixel_tests#pixeldata'
  post 'api/pixels/:suite/url/:urlid/pixels' => 'pixel_tests#addpixeldata'
  
  
  get 'api/testurls/suite/:id' => 'api_test_url#suite'
  get 'api/testurls' => 'api_test_url#index'
  post 'api/testurls' => 'api_test_url#create'
  delete 'api/testurls/:id' => 'api_test_url#delete'
  post 'api/testurls/:id' => 'api_test_url#update'

  
  get 'api/pixeldata' => 'pixel_data#index'
  get 'api/pixeldata/url/:urlid' => 'pixel_data#for_url'
  post 'api/pixeldata' => 'pixel_data#create'
  delete 'api/pixeldata/:id' => 'pixel_data#delete'
  delete 'api/pixeldata/url/:urlid/:pixelname' => 'pixel_data#delete_by_url'
  post 'api/pixeldata/:id' => 'pixel_data#update'

  get 'testruns/index' => 'testruns#index'
  get 'testruns/show/:id' => 'testruns#show'
  get 'testruns/new' => 'testruns#new'
  patch 'testruns/:id' => 'testruns#updatenotes'

  get 'testsuites/pixels' => 'testsuites#index', suitetype: 'pixels'
  get 'testsuites/vanity' => 'testsuites#index', suitetype: 'Vanity'
  get 'testsuites/uci' => 'testsuites#index', suitetype: 'UCI'
  get 'testsuites/seo' => 'testsuites#index', suitetype: 'seo'
  get 'testsuites/pixels/new' => 'testsuites#new_pixel', suitetype: 'pixels'
  post 'testsuites/pixels' => 'testsuites#create', suitetype: 'pixels'

  get 'pixels' => 'testsuites#index', suitetype: 'pixels'

  get 'pixels/new' => 'pixel_tests#new'
  get 'vanity/new' => 'pixel_tests#new', suitetype: 'Vanity'
  get 'seo/new' => 'pixel_tests#new', suitetype: 'seo'
  get 'uci/new' => 'pixel_tests#new', suitetype: 'UCI'
  get 'pixels/:suite' => 'pixel_tests#show'
  post 'pixels/' => 'pixel_tests#create'
  get 'pixels/:suite/edit' => 'pixel_tests#edit'
  

  get 'schedule/new' => 'schedule#new'
  patch 'schedule/:id' => 'schedule#update'
  get 'schedule/:id' => 'schedule#show'
  get 'schedule/edit/:id' => 'schedule#edit'
  delete 'schedule/:id' => 'schedule#delete'
  post 'schedule/disable/:id' => 'schedule#disable'
  post 'schedule/enable/:id' => 'schedule#enable'
  post 'schedule/run/:id' => 'schedule#run'
  get 'schedule/' => 'schedule#index'

  get 'buyflow' => 'testsuites#index', suitetype: 'Buyflow'
  get 'vanity' => 'testsuites#index', suitetype: 'Vanity'
  get 'uci' => 'testsuites#index', suitetype: 'UCI'
  get 'offercode' => 'testsuites#index', suitetype: 'Offercode'
  get 'seo' => 'testsuites#index', suitetype: 'seo'

  
  get 'campaigns/:id/duplicate' => 'campaigns#duplicate'
  get 'campaigns/bybrand/:brand/:environment(.:format)' => 'campaigns#environment'
  get 'campaigns/bybrand/:brand(.:format)' => 'campaigns#brand'

  get '/testsuites/new/offercode' => 'testruns#new', type: 'offercode'
  get '/testsuites/new/buyflow' => 'testruns#new', type: 'buyflow'
  post '/testsuites/offercode/create' => 'testsuites#offercode_create', type: 'offercode'
  post '/testsuites/buyflow/create' => 'testsuites#buyflow_create', type: 'buyflow'

  post '/offerdata/deactivate/:brand/:campaign/:env/:platform' => 'offerdata#deactivate'
  post '/offerdata/update/' => 'offerdata#update'
  post '/offerdata/previewimport/' => 'offerdata#preview'
  get '/offerdata/import/' => 'offerdata#import'

  get '/queue' => 'testruns#simple_queue', suitetype: 'Queue'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#new'

  delete '/buyflow/:id/delete' => 'testsuites#destroy', type: 'buyflow'
  delete '/offercode/:id/delete' => 'testsuites#destroy', type: 'offercode'
  delete '/pixels/:id/delete' => 'testsuites#destroy', type: 'pixels'
  delete '/vanity/:id/delete' => 'testsuites#destroy', type: 'vanity'
  delete '/uci/:id/delete' => 'testsuites#destroy', type: 'uci'
  delete '/seo/:id/delete' => 'testsuites#destroy', type: 'seo'

  get '/download/:id' => 'testsuites#download'

  get '/admin' => 'dashboard#admin_dash'
  post '/admin' => 'dashboard#admin_dash'

  get 'schedule' => 'schedule#index'

  resources :testruns, type: ''

  resources :testsuites
  
  resources :offerdata

  resources :campaigns
  root 'dashboard#index'

end

app/models/locator.rb
class Locator < ActiveRecord::Base
  # maps to Locators table in database

  # setup filter methods for sorting Locators information. shortcut to creating WHERE statements in controller
  scope :brand, -> (brand) { where brand: brand }
  scope :step, -> (step) { where step: step }
  scope :css, -> (css) { where css: css }
  scope :offer, -> (offer) { where offer: offer }

  
end

app/controllers/locators_controller.rb
class LocatorsController < ApplicationController
  include LocatorsHelper
  before_action :set_locator, only: [:show, :edit, :update, :destroy]

  # GET /Locator
  # GET /Locator.json
  def index
    if(params[:search])
      case params[:type]
      when "brand"
        @locators = search(params[:type],params[:searchcontent])
      when "css"
        @locators = search(params[:type], params[:searchcontent])
      when "offer"
        @locators = search(params[:type], params[:searchcontent])
      when "step"
        @locators = search(params[:type], params[:searchcontent])
      end
    else
      @locators = Locator.where(nil)
      # Filter parameters that we want to sort by out of hash, and then set the request to only these values
      filtering_params(params).each do |key, value|
          @locators = @locators.public_send(key, value) if value.present?
      end
    end
    @locators = @locators.all.paginate(:page => params[:page], :per_page => 7)
  end

  # GET /Locator/1
  # GET /Locator/1.json
  def show
  end

  # GET /Locator/new
  def new
    @locator = Locator.new
  end

  # GET /Locator/1/edit
  def edit
  end

  def previewimport
    parse_imports(params)
  end

  def import
    params[:locators].each do |id, locator|
      begin
        locator_obj       = Locator.new()
        locator_obj.css   = locator[:css]
        locator_obj.brand = locator[:brand]
        locator_obj.step  = locator[:step]
        locator_obj.offer = locator[:offer]
        locator_obj.save!
      rescue => e
        flash[:danger] += e.message + " - " + locator[:css]
      end
    end
    redirect_to action: "index"
  end

  # POST /Locator
  # POST /Locator.json
  def create
    @locator = Locator.new(locator_params)

    respond_to do |format|
      if @locator.save
        log_action('Create', current_user ? current_user.username : 'Anonymous', @locator[:id], 'Locator')
        format.html { redirect_to @locator, notice: 'Locator was successfully created.' }
        format.json { render :show, status: :created, location: @locator }
      else
        format.html { render :new }
        format.json { render json: @locator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Locator/1
  # PATCH/PUT /Locator/1.json
  def update
    respond_to do |format|
      if @locator.update(locator_params)
        log_action('Update', current_user ? current_user.username : 'Anonymous', params[:id], 'Locator')
        format.html { redirect_to @locator, notice: 'Locator was successfully updated.' }
        format.json { render :show, status: :ok, location: @locator }
      else
        format.html { render :edit }
        format.json { render json: @locator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Locator/1
  # DELETE /Locator/1.json
  def destroy
    @locator.destroy
    log_action('Delete', current_user ? current_user.username : 'Anonymous', params[:id], 'Locator')
    respond_to do |format|
      format.html { redirect_to locators_path, flash: {success: 'Locator was successfully destroyed.'} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locator
      @locator = Locator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locator_params
      params.require(:locator).permit(:css, :brand, :step, :offer)
    end

    # Campaign filtering limiter
    def filtering_params(params)
      params.slice(:css, :brand, :step, :offer)
    end

    ##
    # Parses imports for the Pixel tests
    def parse_imports(params)
      data = params[:rawdata]
      rows = data.split(/[\n\r]+/)
      rowsandcolumns = []


      rows.each do |row|
        columns = row.split("\t")
        rowsandcolumns.push columns
      end

      @data = rowsandcolumns
  end
end

app/helpers/locators_helper.rb
module LocatorsHelper
	def search(type, string)
  		Locator.where("#{type} like ?", '%' + string + '%')
  	end
end

app/views/locators/_form.html.erb
<%= form_for(@locator) do |f| %>
  <% if @locator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locator.errors.count, "error") %> prohibited this locator from being saved:</h2>

      <ul>
      <% @locator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :css %><br>
    <%= f.text_area :css %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_area :brand %>
  </div>
  <div class="field">
    <%= f.label :step %><br>
    <%= f.text_area :step %>
  </div>
  <div class="field">
    <%= f.label :offer %><br>
    <%= f.text_area :offer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locators/edit.html.erb
<h1>Editing locator</h1>

<%= render 'form' %>

<%= link_to 'Show', @locator %> |
<%= link_to 'Back', locators_path %>

app/views/locators/index.html.erb
<script type="text/javascript">
  $( document ).ready(function() {
      bodyele = $('body');
      bodyele.attr('style', 'background-color:#f5f5f5');
  });
</script>
<div class="panel panel-default panel-body">
  <h1>Listing locators</h1>
  <br>
  <p>

  </p>Search for locators:

  <Br>

  <%= form_tag '/locators', method: :get  do %>
  <div class="input-group col-md-5">
      <%= text_field_tag :searchcontent, params[:searchcontent], {class: "form-control", placeholder: "Search for locators..."} %>
      <div class="input-group-btn" style="min-width: 200px;">
      <%= 
          default_type = params[:type] ? params[:type] : "brand"

          select_tag :type, options_for_select(["brand","css","offer","step"], default_type), class: "form-control" %>
          <%= hidden_field_tag :search, true %>
        </div>
      <span class="input-group-btn">
        <%= submit_tag "Search", class: "form-control btn btn-primary" %>
      </span>
    </div>
  <% end %> 
</div>


<table class="table table-bordered table-hover" style="background-color:#FFFFFF;">
  <thead>
    <tr>
      <th>CSS</th>
      <th>Brand</th>
      <th>Step</th>
      <th>Offer</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @locators.each do |locator| %>
      <tr>
        <td><%= locator.css %></td>
        <td><%= locator.brand %></td>
        <td><%= locator.step %></td>
        <td><%= locator.offer %></td>
        <td><%= link_to 'Show', locator, :class => "btn btn-default" %>
        <%= link_to 'Edit', edit_locator_path(locator), :class => "btn btn-info" %>
        <%= link_to 'Destroy', locator, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @campaigns, renderer: BootstrapPagination::Rails  %>
<br>

<%= link_to 'New Locator', new_locator_path, :class => "btn btn-success"  %>
<br>
<br>
<div class="container">
            <div class='row'>
                
                <%= form_tag("/locators/previewimport", method: "post") do %>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <label>Import Data from Spreadsheet/Selector Scraper</label>
                    </div>    
                    <div class="panel-body">
                        <p>
                            Import data by pasting tab seperated contents from the scraper tool output, or excel sheet
                        </p>
                        <hr>
                        <label for="rawdata">Paste Import Data:</label>
                        <textarea name="rawdata" class="form-control col-md-6" rows=8></textarea>
                    </div>
                    <br>
                    <div class="panel-footer">
                        <input name="commit" type="submit" value="Import" class="btn btn-success" />
                    </div>
                </div>
                
                
                <% end %>
                
                <br/><br/>
                          </div>
        </div>

app/views/locators/new.html.erb
<h1>New locator</h1>

<%= render 'form' %>

<%= link_to 'Back', locators_path %>

app/views/locators/previewimport.html.erb
<div>
	<%= form_tag("/locators/import", method: "post") do %>
	<table class="table table-bordered table-hover">
		<thead>
			<th>CSS</th>
			<th>Brand</th>
			<th>Step</th>
			<th>Offer</th>
		</thead>
		<tbody>
			<% @data.each_with_index do |item, index| %>
			<tr>
				<td><input name='locators[<%= index %>][css]' value='<%= item[0].to_s %>' class="form-control"></td>
				<td><input name='locators[<%= index %>][brand]' value='<%= item[1].to_s %>' class="form-control"></td>
				<td><input name='locators[<%= index %>][step]' value='<%= item[2].to_s %>' class="form-control"></td>
				<td><input name='locators[<%= index %>][offer]' value='<%= item[3].to_s %>' class="form-control"></td>
			
			<tr>
			<% end %>
		</tbody>
	</table>
	<div>
		<input name="commit" type="submit" value="Finalize Import" class="btn btn-success" />
	</div>
	<% end %>
</div>

app/views/locators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Css:</strong>
  <%= @locator.css %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @locator.brand %>
</p>

<p>
  <strong>Step:</strong>
  <%= @locator.step %>
</p>

<p>
  <strong>Offer:</strong>
  <%= @locator.offer %>
</p>

<%= link_to 'Edit', edit_locator_path(@locator) %> |
<%= link_to 'Back', locators_path %>